{% set name = "bm25s" %}
{% set version = "0.2.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/bm25s-{{ version }}.tar.gz
  sha256: e52d6663c68e96f46b1b82efa41a893d268bf979954b0b5ead912a4bfcd173a5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - scipy
    - numpy

test:
  imports:
    - bm25s
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/xhluca/bm25s
  doc_url: https://bm25s.github.io/
  summary: An ultra-fast implementation of BM25 based on sparse matrices.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
