{% set name = "bm25s" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bm25s-{{ version }}.tar.gz
  sha256: 48c271be43eb411dcdc5f3e98ca24ba9723d8be5a388d087a90eb60e13d0d822

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - scipy
    - numpy

test:
  imports:
    - bm25s
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/xhluca/bm25s
  doc_url: https://bm25s.github.io/
  summary: An ultra-fast implementation of BM25 based on sparse matrices.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
